language: generic
include:
- os: linux
  addons:
    apt:
      update: true
      sources:
      - ubuntu-toolchain-r-test
      packages:
      - debootstrap
      - genisoimage
      - p7zip-full
      - squashfs-tools
      - ubuntu-dev-tools
      - dpkg-dev
      - debhelper
      - fakeroot
      - devscripts
sudo: required
git:
  depth: 22
script:
- export LC_ALL=en_US.UTF-8
- export LANG=en_US.UTF-8
- export LANGUAGE=en_US.UTF-8
- chmod +x ./build.sh
- "./build.sh |& tee log.txt"
before_deploy:
- export image_name="`echo *.iso`"
- cat *.iso > "/home/travis/${image_name}"
deploy:
  provider: releases
  api_key:
    secure: LiXcYS3mZzLYFWU6AtagtJTGmuH56pVspEsVFgLJ3MYK+0l2Rz0SkVxTc6CJkBNGOmLC03Q0j5boCejTQ49L+FGg19G4HLrHwUJgHRO2gawxkrB0Sa5+3Dy7RACpMNrJ1izS9oz2DmpTGAoSv7ONiqDSO2SRA6FOHl3h2E3zww8i/jQBoz5+CGWXGmzAZ22hEnLL8J7cEcPffT2xadds2GbuBgsT3+agPPI25fS38f/hlkaiLivxpIOvMIwyve0zASk2t+CZG4x49qzBxYKSSvR4vZHdT3QJDroMwiytyPBN1MAFn46h4SpdvB/BvZ7DUM+IBsem2beCiFV4Rbyq9HQB2zEFZSCUAw9CwV/u/NKz6NjE/FUnrOhcRV02PIE4yLBTNFnweSQIrgLWtA9SIJ177sBOHC+Ai88Qyh7Deip0glyVDFH40+V8QFI+mmB++46OdzHuIhPPzz2goq6MaAAdGqKVGKJUACgzJZYS+MWKm3T6GBxD1c3RURrxhsGn9VaJrylFZvMsZqIoeL3gphmnnfhD5WphL1R+4BNxUJL3EwNIG+9Ejyym8tigSU0or50/FsknlBcnxanAdnW/MECUYt1tooc546h2A9wWyTRl4cPDkAtuQN34tuGPyZcCpOaXcdg6u0a5ycUw/xybNeaKXRqQlgaP6Lhc0FfA1uw=
  file: "/home/travis/${image_name}"
  skip_cleanup: true
  on:
    repo: r0mflip/meilix
after_deploy:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/releases_maintainer.sh;
  fi
- cd scripts && ./mail.py
after_failure:
- cd scripts && ./mail-fail.py
