# This provides us with GCC binary support so we can run bash
language: generic

# Try to supply the packages from Travis so that when we run build.sh we won't
# be required to download them again.
include:
  - os: linux
    addons:
      apt:
        update: true
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - debootstrap
          - genisoimage
          - p7zip-full
          - squashfs-tools
          - ubuntu-dev-tools
          - dpkg-dev
          - debhelper
          - fakeroot
          - devscripts

sudo: required

git:
  depth: 22

script:
  - export LC_ALL=en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US.UTF-8
  - chmod +x ./build.sh
  - ./build.sh |& tee log.txt

before_deploy:
  - export image_name="`echo *.iso`"
  - cat *.iso > "/home/travis/${image_name}"


deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "mD9aiOuRxhmGEjB8vgucZJDlSoDaBAE9tlJyDwhmymMLN9UFiV+swWj0obvkqnTVFjqmpLhWiXoQzRy5gzie4/0IOAVoxHvUNy8DgOF2CPGRR1hcT5PHim0JyVrxAf6GfM/qMgZtW6r63pMoU/A2hpleavN7M0FsgibLID8KefIrsLxFkuX80LqolRT9UuHnKKmod7hcHIvHOFLZLsbAlk7tVm4yk4yspmGsTz+2sPduEkVmDFZfIMsQkIh3sCdV3e+kRfLSR576/ZqYPlFQVZeJLfjqhyb8sUnZJXRp3E4Ot+lhPe6qrL0wy7VTdeW59m+nQiBL14Pj4GPUBbjPjTOhmSg055msa77J/iGgnbtxk/pxMxZU1UUgr7KyihURe5M5lBuRUv93XNgbT17eQG8ryZ/+fAlcAdmC21fGUawiL03/pwLHnLk/Dg8STKqZ+ekhjFzeS8pXq9UhJEUjWVjk5CeeBzr7Q5iXtX/37i0tgn6EOoFxhKow0Z3plEHG8rrXAFUG923QTBxWScmP1jXhsZb0ccmmcV4rDuTtRkYUS2I2ruiBAobjYnGhf4Vmy1SKr9GUGPBTKXjycBtdtGp7wCKh60YRwJWgT0MRf5d0LyJrzbgH5TVEtf/JH132Bw4YXTCZVAa04z8BAS+lqDwnOpkDZGjzeWvlPUAcCLU="
    file_glob: true # http://stackoverflow.com/a/28579635/1320237
    file: "/home/travis/${image_name}"
    on:
      all_branches: true

after_deploy:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./scripts/releases_maintainer.sh; fi'
  - cd scripts && ./mail.py
  
after_failure:
  - cd scripts && ./mail-fail.py
